# Generated by Django 5.1.3 on 2025-04-29 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
