# Generated by Django 5.1.3 on 2025-05-02 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_alter_detail_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.RemoveField(
            model_name='detail',
            name='img',
        ),
    ]
