# Generated by Django 5.1.3 on 2025-05-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_profile_remove_detail_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.AddField(
            model_name='detail',
            name='img',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
