# Generated by Django 4.2.11 on 2024-11-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_post_post_author_post_post_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
