# Generated by Django 5.1.3 on 2025-05-02 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_delete_profile_detail_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_user', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='media/media')),
            ],
        ),
        migrations.AlterField(
            model_name='detail',
            name='img',
            field=models.ImageField(null=True, upload_to='media/media'),
        ),
    ]
