# Generated by Django 5.1.3 on 2024-11-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_comment_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
