# Generated by Django 5.1.3 on 2025-05-07 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_profileimage_alter_detail_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='img',
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='image_user',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='img',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
