# Generated by Django 5.1.3 on 2025-05-14 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0006_remove_detail_img_alter_profileimage_image_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='img',
            field=models.ImageField(default='media/tlok.jpeg', null=True, upload_to='media/'),
        ),
    ]
