# Generated by Django 5.1.3 on 2025-06-14 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0007_alter_profileimage_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileimage',
            name='img',
            field=models.ImageField(null=True, upload_to='media/profiles/'),
        ),
    ]
